### PR TITLE
fix #274: keep track of done processes

### LINKED ISSUE #274: Process B fails quickly results in "process A depends on B, but it isn't running"
## Defect

When process A depends on B completing successfully, process A runs if B fails quickly. It should not run if B fails, regardless how quickly.

- [x] Included the relevant configuration snippet
- [x] Included the relevant process-compose log (log location: `process-compose info`)
- [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Steps or code to reproduce the issue:

process-compose.json:
```json
{
  "processes": {
    "bundle-install": { "command": "sleep 10", "namespace": "default" },
    "configure": { "command": "diff a b", "namespace": "default" },
    "mysql": {
      "availability": { "max_restarts": 5, "restart": "on_failure" },
      "command": "sleep 100",
      "namespace": "mysql.mysql",
      "readiness_probe": {
        "exec": {
          "command": "echo mysql"
        },
        "failure_threshold": 5,
        "initial_delay_seconds": 2,
        "period_seconds": 10,
        "success_threshold": 1,
        "timeout_seconds": 4
      }
    },
    "mysql-configure": {
      "command": "sleep 3",
      "depends_on": { "mysql": { "condition": "process_healthy" } },
      "namespace": "mysql.mysql"
    },
    "prepare-db": {
      "command": "echo PREPARE DB",
      "depends_on": {
        "bundle-install": { "condition": "process_completed_successfully" },
        "configure": { "condition": "process_completed_successfully" },
        "mysql-configure": { "condition": "process_completed_successfully" }
      },
      "namespace": "default"
    },
    "web": {
      "command": "sleep 100",
      "depends_on": {
        "bundle-install": { "condition": "process_completed_successfully" },
        "configure": { "condition": "process_completed_successfully" },
        "prepare-db": { "condition": "process_completed_successfully" }
      },
      "namespace": "default"
    }
  },
  "shell": { "shell_argument": "-c", "shell_command": "/bin/bash" }
}
```

#### Expected result:

```
24-11-07 16:04:39.275 ERR Error: process prepare-db depended on configure to complete successfully, but it exited with status 2
24-11-07 16:04:39.275 ERR Error: process prepare-db won't run
```

#### Actual result:

```
24-11-07 16:04:49.281 ERR Error: process web depends on configure, but it isn't running
24-11-07 16:04:49.281 ERR Error: process web depends on prepare-db, but it isn't running
24-11-07 16:04:49.286 INF Started command=["/bin/bash","-c","sleep 100"] process=web
```

#### Full log:

This run had both the good case and the bad case happening:
```
24-11-07 16:04:39.260 INF Process Compose v1.34.0
24-11-07 16:04:39.261 INF Loaded project from nix/process-compose-enterprise.json
24-11-07 16:04:39.261 INF Global shell command: /bin/bash -c
24-11-07 16:04:39.261 INF start http server listening :8080
24-11-07 16:04:39.261 DBG Spinning up 6 processes. Order: ["configure" "mysql" "mysql-configure" "bundle-install" "prepare-db" "web"]
24-11-07 16:04:39.261 INF web is waiting for bundle-install to complete successfully
24-11-07 16:04:39.262 INF mysql-configure is waiting for mysql to be healthy
24-11-07 16:04:39.262 INF prepare-db is waiting for configure to complete successfully
24-11-07 16:04:39.264 INF Started command=["/bin/bash","-c","sleep 100"] process=mysql
24-11-07 16:04:39.264 INF Started command=["/bin/bash","-c","sleep 10"] process=bundle-install
24-11-07 16:04:39.265 INF Started command=["/bin/bash","-c","diff a b"] process=configure
24-11-07 16:04:39.275 INF Exited exit_code=2 process=configure
24-11-07 16:04:39.275 ERR Error: process prepare-db depended on configure to complete successfully, but it exited with status 2
24-11-07 16:04:39.275 ERR Error: process prepare-db won't run
24-11-07 16:04:41.264 DBG mysql_ready_probe started monitoring
24-11-07 16:04:41.275 INF Started command=["/bin/bash","-c","sleep 3"] process=mysql-configure
24-11-07 16:04:44.288 INF Exited exit_code=0 process=mysql-configure
24-11-07 16:04:49.281 INF Exited exit_code=0 process=bundle-install
24-11-07 16:04:49.281 ERR Error: process web depends on configure, but it isn't running
24-11-07 16:04:49.281 ERR Error: process web depends on prepare-db, but it isn't running
24-11-07 16:04:49.286 INF Started command=["/bin/bash","-c","sleep 100"] process=web
24-11-07 16:06:19.279 INF Exited exit_code=0 process=mysql
24-11-07 16:06:29.315 INF Exited exit_code=0 process=web
24-11-07 16:06:29.315 INF Project completed
24-11-07 16:06:31.008 DBG Shutting down 0 processes. Order: []
24-11-07 16:06:32.009 DBG Logs monitoring canceled
24-11-07 16:06:32.011 DBG TUI Wait stopped
24-11-07 16:06:32.011 INF Thank you for using process-compose
```

### PR DESCRIPTION
**Pull request by secobarbital**
Keep track of done processes in case we have to start a process that depends on another process that has already exited.

PS I would love to add a test but I don't know how to run tests in this project!

Closes #274

### CODE REVIEW

**Comment by secobarbital** [comment]
The change I made is the least intrusive, but I wonder if it is better to maintain just a single list of processes which includes all processes in every stage of their lifecycle (pending, started, skipped, completed). That would probably require changes in the logic of some of the functions that access this list.

**Review by F1bonacc1 — APPROVED** [review]
I pulled and tested it locally.
Looks good!
Good catch, thanks!

**Comment by F1bonacc1** [comment]
> PS I would love to add a test but I don't know how to run tests in this project!

I use `make` so I usually do `make testrace` which is equivalent to `go test -race ./src/...`

**Comment by secobarbital** [comment]
@F1bonacc1 I noticed this was mentioned in the [v1.40.0 Release Notes](https://github.com/F1bonacc1/process-compose/releases/tag/v1.40.0) but the code was not merged 😅

**Comment by F1bonacc1** [comment]
@secobarbital you are right, not sure what happened there... 🙃 
Merged and released as v1.40.1

**Pull request merged**
