### PR TITLE
Bump `github.com/rivo/tview` from `v0.0.0-20240307173318-e804876934a1` to `v0.0.0-20240505185119-ed116790de0f`

### PR DESCRIPTION
**Pull request by shivaraj-bh**
This version includes https://github.com/rivo/tview/issues/959, which resolves https://github.com/F1bonacc1/process-compose/issues/186.

### CODE REVIEW

**Comment by F1bonacc1** [comment]
Hey @shivaraj-bh,

Thanks for finding the solution so quickly!
Unfortunately, this version breaks the `F1` shortcuts view.
Can you confirm that this is the case for you as well?

**Previous version:**
image


**New version:**
image

**Comment by shivaraj-bh** [comment]
Screenshot 2024-05-17 at 10 14 46 PM

It seems to not collapse when the `Close` button is not there

**Comment by shivaraj-bh** [comment]
It is not to do with the button. Anytime there is more than one item, the dialog collapses and transforms into a fixed-size dialog at the top center.

**Comment by shivaraj-bh** [comment]
Fixed in https://github.com/F1bonacc1/process-compose/commit/8877e7f4b59ff446b7461c4cb510641972241315

**Pull request closed without merging**
